BEGIN TRANSACTION TABLE_CREATION

USE VisitorManagement
GO

IF OBJECT_ID ('dbo.EntriesExits', 'U') IS NOT NULL  
	BEGIN
		DROP TABLE EntriesExits;
	END
GO

IF OBJECT_ID ('dbo.CustomerSites', 'U') IS NOT NULL
	BEGIN
		DROP TABLE CustomerSites;
	END
GO 

IF OBJECT_ID ('dbo.Customers', 'U') IS NOT NULL
	BEGIN
		DROP TABLE Customers;
	END
GO  

BEGIN
	CREATE TABLE Customers
	(
		Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1903831,1)
		,CustomerName NVARCHAR(50) NOT NULL
		,Address NVARCHAR(250) NOT NULL
		,ContactNumber NVARCHAR(16) NOT NULL
		,Country NVARCHAR(70) NOT NULL
	)
END
GO

BEGIN
	CREATE TABLE CustomerSites
	(
		Id BIGINT NOT NULL PRIMARY KEY IDENTITY(123211,1)
		,CustomerID BIGINT NOT NULL FOREIGN KEY REFERENCES Customers(Id)
		,Sitename NVARCHAR(50) NOT NULL
		,Address NVARCHAR(250)
	)
END
GO

BEGIN
	CREATE TABLE EntriesExits
	(
		Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1)
		,SiteId BIGINT NOT NULL FOREIGN KEY REFERENCES CustomerSites(Id)
		,Direction NVARCHAR(5) NOT NULL
		,GateNumber INT NOT NULL
		,Time DATETIME NOT NULL
	)
END
GO

COMMIT TRANSACTION TABLE_CREATION;